### ISSUE TITLE
Got this error

### ISSUE THREAD

**Issue by RyuBcn** [Boren/PokemonGO-IV-Renamer#11]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from pgoapi import PGoApi
  File "/usr/lib/python2.6/site-packages/pgoapi/**init**.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/usr/lib/python2.6/site-packages/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/usr/lib/python2.6/site-packages/pgoapi/rpc_api.py", line 41, in <module>
    from pgoapi.utilities import f2i, h2f, to_camel_case, get_time_ms, get_format_time_diff
  File "/usr/lib/python2.6/site-packages/pgoapi/utilities.py", line 35, in <module>
    from geopy.geocoders import GoogleV3
  File "/usr/lib/python2.6/site-packages/geopy/**init**.py", line 11, in <module>
    from geopy.point import Point
  File "/usr/lib/python2.6/site-packages/geopy/point.py", line 9, in <module>
    from geopy.format import (
  File "/usr/lib/python2.6/site-packages/geopy/format.py", line 119
    for n, d
      ^
SyntaxError: invalid syntax

Newbie on Python here, maybe some library isn't properly installed? thank you

**Comment by RyuBcn** [comment]
solved installing python3 but now stuck on "login error"
