### ISSUE TITLE
KeyError: 'NICKNAME_POKEMON'

### ISSUE THREAD

**Issue by sahayes1** [Boren/PokemonGO-IV-Renamer#24]
--------- Flareon ---------
CP 775 - 14/12/12 84.44%
Traceback (most recent call last):
  File "main.py", line 215, in <module>
    Renamer().start()
  File "main.py", line 62, in start
    self.rename_pokemons()
  File "main.py", line 172, in rename_pokemons
    result = response['responses']['NICKNAME_POKEMON']['result']
KeyError: 'NICKNAME_POKEMON'

**Comment by eratio08** [comment]
Im getting the same error

Traceback (most recent call last):
File "main.py", line 215, in <module>
Renamer().start()
File "main.py", line 62, in start
self.rename_pokemons()
File "main.py", line 172, in rename_pokemons
result = response['responses']['NICKNAME_POKEMON']['result']
KeyError: 'NICKNAME_POKEMON'

seems to be introduced with 38ef306ef0b0ac126d7bb2559ab7ba6c97dc0c17

**Comment by eratio08** [comment]
> in b4: no python guy

The response Object of the api.call seems to be empty - is this because of the 10s call limit?

**Comment by eratio08** [comment]
The delay should be that to the call limit (I read some where it was 10s now - but not sure)

**Comment by edevnull** [comment]
```
Traceback (most recent call last):
  File "main.py", line 244, in <module>
    Renamer().start()
  File "main.py", line 68, in start
    self.rename_pokemon()
  File "main.py", line 199, in rename_pokemon
    result = response['responses']['NICKNAME_POKEMON']['result']
KeyError: 'NICKNAME_POKEMON'
```

Started with:

`python main.py -a google -u xxx@gmail.com -p xxx --format "%name%percent"`
