### ISSUE TITLE
Error since lastest pull.

### ISSUE THREAD

**Issue by omlet05** [Boren/PokemonGO-IV-Renamer#59]
Hi,
I've got this issue into docker or local.

`Start renamer
Traceback (most recent call last):
  File "main.py", line 280, in <module>
    Renamer().start()
  File "main.py", line 67, in start
    self.setup_api()
  File "main.py", line 81, in setup_api
    self.get_location()
  File "main.py", line 264, in get_location
    res = prog.match(self.config.location)
TypeError: expected string or buffer`

regards,

**Comment by pablossp** [comment]
Checking the code, you need to pass the location parameter too now with -l

**Comment by Boren** [comment]
Fixed with #61
