### ISSUE TITLE
Unknown Error 

### ISSUE THREAD

**Issue by JaydenHamence** [Boren/PokemonGO-IV-Renamer#60]
Start renamer
Traceback (most recent call last):
  File "main.py", line 280, in <module>
    Renamer().start()
  File "main.py", line 67, in start
    self.setup_api()
  File "main.py", line 81, in setup_api
    self.get_location()
  File "main.py", line 264, in get_location
    res = prog.match(self.config.location)
TypeError: expected string or buffer

**Comment by eratio08** [comment]
yeah thats because the README isn't updated yes - you will habe to use "-L" for local settings and "-l" to provide a location (longitudes and latitudesm use google maps to get yours)
