### ISSUE TITLE
won't start

### ISSUE THREAD

**Issue by chriscrutt** [Boren/PokemonGO-IV-Renamer#79]
I fixed the print by putting all the parenthesis in, now i get

```
Start renamer
Traceback (most recent call last):
  File "main.py", line 282, in <module>
    Renamer().start()
  File "main.py", line 68, in start
    self.setup_api()
  File "main.py", line 82, in setup_api
    self.get_location()
  File "main.py", line 266, in get_location
    res = prog.match(self.config.location)
TypeError: expected string or bytes-like object
```

**Comment by Boren** [comment]
At this time, only Python 2.7 is supported.
